#### Numpy is python package used for numerical computaions (indexed by tuple of non negative integers)
#### Number of dimensions is called Rank of array
#### Tuple of integers giving size across each dimension is called Shape
#### Arrays have elements of same data type

In [1]:
import numpy as np

In [2]:
my_lst = [1,2,3,4,5,6]

In [3]:
print(my_lst)

[1, 2, 3, 4, 5, 6]


In [4]:
type(my_lst)

list

In [5]:
arr1 = np.array(my_lst, dtype = int)

In [6]:
print(arr1)

[1 2 3 4 5 6]


In [7]:
type(arr1)

numpy.ndarray

In [10]:
print(arr1.ndim)
print(arr1.shape)

1
(6,)


In [25]:
print(arr1)

[1 2 3 4 5 6]


In [26]:
arr12 = arr1.reshape(1,6)

In [27]:
print(arr12)

[[1 2 3 4 5 6]]


In [28]:
print(arr12.ndim)
print(arr12.shape)

2
(1, 6)


In [29]:
arr12.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [30]:
print(arr12)

[[1 2 3 4 5 6]]


In [31]:
print(arr12.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [14]:
print(type(arr1))
print(len(arr1))
print(arr1.ndim)
print(arr1.shape)   # Gives size along each dimension

<class 'numpy.ndarray'>
6
1
(6,)


In [15]:
arr2 = arr1.reshape(3,2)

In [16]:
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
print(arr1.shape)    # 6 elements and 1 dimension
print(arr2.shape)    # 3 elements and 2 dimension (3 rows 2 columns)
print(arr2.ndim)

(6,)
(3, 2)
2


In [32]:
arr3 = arr1.reshape(2,3)

In [33]:
print(arr1.shape)    # 6 elements and 1 dimension
print(arr2.shape)    # 3 elements and 2 dimension
print(arr3.shape)    # 2 elements and 3 dimension (2 rows 3 columns)

(6,)
(3, 2)
(2, 3)


In [34]:
print(arr3)

[[1 2 3]
 [4 5 6]]


In [35]:
arr4 = arr1.reshape(3,-1)   # Here there are 3 rows. With -1 other dimension would be calculated automatically

In [36]:
print(arr4)
print(arr4.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [37]:
print(arr4.shape)

(3, 2)


In [38]:
print(arr4.ndim)

2


In [39]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

In [40]:
mul_arr = np.array([my_lst1,my_lst2,my_lst3])

In [41]:
print(mul_arr)
print(mul_arr.shape)
print(mul_arr.ndim)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)
2


In [42]:
mul_arr1= mul_arr.reshape(1,15)

In [43]:
print(mul_arr1)

[[1 2 3 4 5 2 3 4 5 6 9 7 6 8 9]]


In [44]:
mul_arr1.shape

(1, 15)

In [45]:
mul_arr1.ndim

2

#### Num-py attributes

In [51]:
a = np.array([[1,2,3],[4,5,6]])

In [52]:
print(a)

[[1 2 3]
 [4 5 6]]


In [53]:
a.shape

(2, 3)

In [54]:
a.ndim

2

In [55]:
print(a)

[[1 2 3]
 [4 5 6]]


In [56]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [57]:
r = range(24)

In [58]:
print(r)

range(0, 24)


In [59]:
a1 = np.arange(24)

In [60]:
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [61]:
a21 = np.arange(24).reshape(6,-1)

In [62]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
a21.shape

(6, 4)

In [64]:
a1.ndim

1

In [66]:
a1.shape   # 24 elements distributed across 1 axis

(24,)

In [67]:
b1 = a1.reshape(6,4,1)               # 6 vectors with 4 rows and 1 column for each vector
print(b1)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [68]:
print(b1.ndim)
print(b1.shape)

3
(6, 4, 1)


#### Num-py Operations

In [69]:
x = np.array([1,2,3,4,5], dtype = np.int8)

In [70]:
print(x)

[1 2 3 4 5]


In [71]:
print(x.itemsize)

1


In [72]:
x = np.array([1,2,3,4,5], dtype = np.float32)
print(x.itemsize)

4


In [73]:
print(x)

[1. 2. 3. 4. 5.]


In [74]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [75]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [76]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [77]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [78]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [79]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [80]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [81]:
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]


In [82]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [83]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [84]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [85]:
print(np.sum(x))

10.0


In [86]:
print(np.sum(y))

26.0


In [87]:
print(np.sum(x, axis = 0))           # Compute sum of columns

[4. 6.]


In [88]:
print(np.sum(x, axis = 1))          # Compute sum of rows

[3. 7.]


In [89]:
print(np.sum(y, axis = 0))           # Compute sum of columns

[12. 14.]


In [90]:
print(np.sum(y, axis = 1))          # Compute sum of rows

[11. 15.]


In [91]:
print(np.sum(x+y))
print((x+y))

36.0
[[ 6.  8.]
 [10. 12.]]


In [92]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [93]:
print(np.power(x,y))         # 1st Array element raised to the power of Second Array Element

[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


In [94]:
print(np.power(y,x)) 

[[   5.   36.]
 [ 343. 4096.]]
